//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
//  
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Scaffold.API.V1.Models
{
    /// <summary>
    /// 역할(권한그룹) 내 사용자
    /// </summary>
    public partial class UserRole {

        public UserRole()
        {
            OnCreated();
        }

        /// <summary>
        /// 사용자 아이디
        /// </summary>
        public virtual Guid UserId { get; set; }

        /// <summary>
        /// 역할(권한그룹) 아이디
        /// </summary>
        public virtual Guid RoleId { get; set; }

        /// <summary>
        /// 역할 정보
        /// </summary>
        public virtual Role Role { get; set; }

        /// <summary>
        /// 사용자 정보
        /// </summary>
        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        public override bool Equals(object obj)
        {
          UserRole toCompare = obj as UserRole;
          if (toCompare == null)
          {
            return false;
          }

          if (!Object.Equals(this.UserId, toCompare.UserId))
            return false;
          if (!Object.Equals(this.RoleId, toCompare.RoleId))
            return false;

          return true;
        }

        public override int GetHashCode()
        {
          int hashCode = 13;
          hashCode = (hashCode * 7) + UserId.GetHashCode();
          hashCode = (hashCode * 7) + RoleId.GetHashCode();
          return hashCode;
        }

        #endregion
    }

}
