//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
//  
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Net7Api.Models
{
    /// <summary>
    /// 사용자 정보
    /// </summary>
    public partial class User {

        public User()
        {
            this.IsDeleted = false;
            OnCreated();
        }

        /// <summary>
        /// 사용자 아이디
        /// </summary>
        public virtual Guid Id { get; set; }

        /// <summary>
        /// 접속 실패 회수
        /// </summary>
        public virtual int AccessFailedCount { get; set; }

        /// <summary>
        /// 사번 등 식별 코드
        /// </summary>
        public virtual string Code { get; set; }

        /// <summary>
        /// 병행지문
        /// </summary>
        public virtual string ConcurrencyStamp { get; set; }

        /// <summary>
        /// 이메일
        /// </summary>
        public virtual string Email { get; set; }

        /// <summary>
        /// 이메일 승인여부
        /// </summary>
        public virtual bool EmailConfirmed { get; set; }

        /// <summary>
        /// 잠금 활성화 여부
        /// </summary>
        public virtual bool LockoutEnabled { get; set; }

        /// <summary>
        /// 잠금 만료 시간
        /// </summary>
        public virtual DateTime? LockoutEnd { get; set; }

        /// <summary>
        /// 사용자명
        /// </summary>
        public virtual string Name { get; set; }

        /// <summary>
        /// 표준화 된 이메일
        /// </summary>
        public virtual string NormalizedEmail { get; set; }

        /// <summary>
        /// 표준화 된 로그인 아이디
        /// </summary>
        public virtual string NormalizedUserName { get; set; }

        /// <summary>
        /// 비밀번호 해쉬
        /// </summary>
        public virtual string PasswordHash { get; set; }

        /// <summary>
        /// 전화번호
        /// </summary>
        public virtual string PhoneNumber { get; set; }

        /// <summary>
        /// 전화번호 확인 여부
        /// </summary>
        public virtual bool PhoneNumberConfirmed { get; set; }

        /// <summary>
        /// 보안 지문
        /// </summary>
        public virtual string SecurityStamp { get; set; }

        /// <summary>
        /// 2차 인증 활성화 여부
        /// </summary>
        public virtual bool TwoFactorEnabled { get; set; }

        /// <summary>
        /// 삭제 여부
        /// </summary>
        public virtual bool IsDeleted { get; set; }

        /// <summary>
        /// 비밀번호 변경 일시
        /// </summary>
        public virtual DateTime? PasswordChangeDate { get; set; }

        /// <summary>
        /// 로그인아이디 (사용안함)
        /// </summary>
        public virtual string LoginId { get; set; }

        /// <summary>
        /// 이전 아이디
        /// </summary>
        public virtual string OldId { get; set; }


        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
