//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
//  
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Net7Api.Models
{
    /// <summary>
    /// 역할(권한 그룹)
    /// </summary>
    public partial class Role {

        public Role()
        {
            this.RoleClaims = new List<RoleClaim>();
            this.UserRoles = new List<UserRole>();
            OnCreated();
        }

        /// <summary>
        /// 역할(권한그룹) 아이디
        /// </summary>
        public virtual Guid Id { get; set; }

        /// <summary>
        /// 병행지문
        /// </summary>
        public virtual string ConcurrencyStamp { get; set; }

        /// <summary>
        /// 역할(권한 그룹)명
        /// </summary>
        public virtual string Name { get; set; }

        /// <summary>
        /// 표준화 된 역할(권한 그룹)명
        /// </summary>
        public virtual string NormalizedName { get; set; }

        /// <summary>
        /// 역할 권한 목록
        /// </summary>
        public virtual IList<RoleClaim> RoleClaims { get; set; }

        /// <summary>
        /// 역할(권한그룹) 내 사용자 목록
        /// </summary>
        public virtual IList<UserRole> UserRoles { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
