//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
//  
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace Net7Api.Models
{
    /// <summary>
    /// 역할(권한그룹) 권한
    /// </summary>
    public partial class RoleClaim {

        public RoleClaim()
        {
            OnCreated();
        }

        /// <summary>
        /// 권한 아이디
        /// </summary>
        public virtual int Id { get; set; }

        /// <summary>
        /// 권한 타입
        /// </summary>
        public virtual string ClaimType { get; set; }

        /// <summary>
        /// 권한 값
        /// </summary>
        public virtual string ClaimValue { get; set; }

        /// <summary>
        /// 역할(권한그룹) 아이디
        /// </summary>
        public virtual Guid RoleId { get; set; }

        /// <summary>
        /// 역할 정보
        /// </summary>
        public virtual Role Role { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
